name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          if [ -z "${{ secrets.FLY_API_TOKEN }}" ]; then
            echo "::error::FLY_API_TOKEN is not set in repository secrets"
            echo "Please add your Fly.io API token as a repository secret named FLY_API_TOKEN"
            exit 1
          fi
      - name: Initialize Fly.io app
        run: |
          # Extract app name from fly.toml
          APP_NAME=$(grep -m 1 "app = " fly.toml | cut -d '"' -f 2)
          echo "App name from fly.toml: $APP_NAME"

          # Force create/launch the app with explicit organization
          echo "Creating/launching app on Fly.io: $APP_NAME"
          flyctl launch --name $APP_NAME --org personal --no-deploy || true
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: flyctl deploy --org personal --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}